/* Regenerate src/text/dbcs.ts from Unicode.org mapping tables.
 *
 * Double-byte codepages are stored as a compact string: lead-byte ranges
 * plus a run-length encoded map, so the shipped module stays small enough
 * for a browser bundle while covering every mapped code point.
 *
 * Usage: node tools/gen-dbcs.mjs <dir-with-.TXT-tables>
 */

import { readFileSync, writeFileSync } from 'node:fs';

const PAGES = [
  ['CP932', 'CP932.TXT'],
  ['BIG5', 'BIG5.TXT'],
  ['GB2312', 'GB2312.TXT'],
  ['CP949', 'CP949.TXT'],
  ['JOHAB', 'JOHAB.TXT']
];

const dir = process.argv[2];
if (!dir) {
  console.error('usage: node tools/gen-dbcs.mjs <table-dir>');
  process.exit(1);
}

/** Pack (dbcsCode -> unicode) pairs as base36 deltas: "k:v" runs. */
const pack = (pairs) => {
  pairs.sort((a, b) => a[0] - b[0]);
  const parts = [];
  let lastK = 0, lastV = 0;
  for (const [k, v] of pairs) {
    parts.push((k - lastK).toString(36) + ',' + (v - lastV).toString(36));
    lastK = k;
    lastV = v;
  }
  return parts.join(';');
};

let out = `/* nasjidwg — double-byte codepage tables (CJK).
 * GENERATED by tools/gen-dbcs.mjs from the Unicode.org mapping tables;
 * do not edit by hand. Entries are base36 delta pairs "dCode,dUnicode".
 */

export const DBCS_PACKED: Record<string, string> = {
`;

for (const [name, file] of PAGES) {
  const pairs = [];
  const leads = new Set();
  for (const line of readFileSync(`${dir}/${file}`, 'utf8').split('\n')) {
    const m = line.match(/^0x([0-9A-Fa-f]{2,4})\s+0x([0-9A-Fa-f]{4})/);
    if (!m) continue;
    const code = parseInt(m[1], 16);
    const uni = parseInt(m[2], 16);
    if (code < 0x100) continue;           /* single bytes live elsewhere */
    pairs.push([code, uni]);
    leads.add(code >> 8);
  }
  out += `  ${name}: '${pack(pairs)}',\n`;
}
out += '};\n\n';

/* single-byte halves of the same pages */
out += 'export const DBCS_SINGLE: Record<string, string> = {\n';
for (const [name, file] of PAGES) {
  const pairs = [];
  for (const line of readFileSync(`${dir}/${file}`, 'utf8').split('\n')) {
    const m = line.match(/^0x([0-9A-Fa-f]{2})\s+0x([0-9A-Fa-f]{4})/);
    if (!m) continue;
    const code = parseInt(m[1], 16);
    const uni = parseInt(m[2], 16);
    if (code < 0x80 || code > 0xff) continue;
    pairs.push([code, uni]);
  }
  out += `  ${name}: '${pack(pairs)}',\n`;
}
out += '};\n';

writeFileSync(new URL('../src/text/dbcs.ts', import.meta.url), out);
console.log('wrote src/text/dbcs.ts');
